title: ğ™¶ğ™´ğ™½ğ™¾ğš…ğ™°
description: Student-led STEM articles and research
url: "https://www.genovag.org"
baseurl: ""


remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

custom_css:
  - /assets/css/custom.css
custom_js:
  - /assets/js/reveal.js

minimal_mistakes_skin: "default"
future: true
